{"name": "Проверяем невозможность авторизации с несуществующим паролем и логином", "status": "passed", "steps": [{"name": "Создаем случайны набор данных", "status": "passed", "steps": [{"name": "Создаем случайный емейл", "status": "passed", "start": 1714564830063, "stop": 1714564830063}], "start": 1714564830063, "stop": 1714564830063}], "start": 1714564830063, "stop": 1714564830520, "uuid": "026ed14c-d199-4886-8158-46813e2d65d6", "historyId": "801e79f4d94cbf1b96d6fdcfea6b5b26", "testCaseId": "801e79f4d94cbf1b96d6fdcfea6b5b26", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_wrong_password_and_login_impossible", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "Glavnyi-PC"}, {"name": "thread", "value": "14112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}